import React from 'react'
import './Blog.css'

const Blog = () => {
    return (
        <div className='blog'>
            <div className="table">
                <div className="title">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi soluta repellendus quidem sint aut dignissimos velit architecto, veritatis mollitia deserunt sapiente ipsam itaque officia eaque, voluptatem voluptas expedita perferendis? Tempora dolores modi reiciendis voluptatum, consectetur labore iusto dolorum voluptates blanditiis eveniet accusantium, exercitationem quae? Rerum.</div>
                <div className="details">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium quod voluptates ea?</div>
            </div>
            <p className="content">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis, enim animi praesentium, quidem sequi pariatur facere rerum labore ullam soluta doloribus tempora illo aut a excepturi error nemo officia unde, nesciunt provident atque ea vitae. Unde enim minima consequuntur explicabo fugiat adipisci maiores dignissimos doloremque ipsum dolor! Ea asperiores minus iusto totam odio dolore rem, quia voluptatum dicta quod? Soluta ipsa eos enim, ullam possimus totam inventore aliquid sapiente provident reprehenderit perferendis quaerat rerum doloremque amet, non iusto eveniet animi. Cum praesentium incidunt velit ipsa vero architecto adipisci assumenda tempore maxime, quas recusandae voluptatem repellendus similique aut provident amet quam omnis sed consequatur in autem quibusdam? In qui aperiam sed quaerat eligendi ratione accusantium quia blanditiis facilis voluptates saepe nihil, atque repudiandae, animi quo? Ipsam itaque explicabo quae perspiciatis iure saepe. Ad dolorum debitis ut excepturi inventore tempora, cupiditate necessitatibus! Dicta omnis, fugit fuga distinctio odit corrupti natus, eveniet pariatur libero officia nostrum dolor tempore. Vitae quisquam officia ad sapiente consequuntur. Numquam recusandae esse dolor, laboriosam aspernatur magni saepe mollitia laborum nobis, consequuntur ipsa quisquam maxime cupiditate sequi fugit nisi nemo quis delectus in odio architecto! Facere rem repellat numquam minima accusantium corrupti quia molestias similique eaque magni quos doloribus perferendis error, culpa dicta, repellendus corporis? Consectetur libero recusandae inventore illum quasi molestiae cupiditate blanditiis quos autem alias praesentium ad consequuntur ex molestias minima non nobis, sed sunt animi expedita distinctio impedit saepe ipsum? Minus eligendi tempore debitis sunt deserunt labore eveniet soluta ullam, error cupiditate deleniti dolorem ad et sequi, reiciendis vitae. Deserunt aperiam eum voluptas sunt fuga ad explicabo quibusdam cumque facere, doloribus fugiat sint voluptatem excepturi quae alias quam! Officiis, dignissimos voluptates? Odit corporis error veritatis dolorem maxime aliquam nam vitae rem sint voluptas? Perferendis, repellendus pariatur. Totam alias ab omnis molestiae sed, perspiciatis nam reprehenderit commodi?</p>
        </div>
    )
}

export default Blog